//! A reader for the one JSON shape the Z80 vectors come in.
//!
//! Not a general JSON parser and not trying to be. `testrunner` is dev-only, but
//! adding `serde_json` here would put it in the workspace lock file and in every
//! contributor's build, to read a format that is generated by one program and
//! never hand-edited. So this scans for the keys it needs and rejects anything it
//! does not recognise — loudly, by name, because a reader that guessed would
//! compare the core against a trace it had misread and report success.

use crate::z80fmt::{Case, Cycle, Port, RamEntry, State};

/// What can be wrong with a vector JSON file.
#[derive(Debug)]
pub struct JsonError(String);

impl core::fmt::Display for JsonError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.write_str(&self.0)
    }
}

impl std::error::Error for JsonError {}

fn err<T>(msg: impl Into<String>) -> Result<T, JsonError> {
    Err(JsonError(msg.into()))
}

/// Decodes a pin string into `(rd, wr, mreq, ioreq)`.
///
/// The suite writes four characters — `r`, `w`, `m`, `i`, each replaced by `-`
/// when that pin is inactive — but only the five combinations below occur, and
/// this accepts only those five. A per-character decoder would look equivalent
/// and is not: it accepts `"rwmi"`, which asserts RD and WR together and MREQ and
/// IORQ together. Neither pair is ever simultaneously low on a real Z80, so such a
/// string is a pattern this reader does not understand — exactly what the check
/// exists to catch. A whitelist says so; a character loop quietly agrees to it.
///
/// # Errors
///
/// If `s` is not one of the five confirmed patterns. That includes a pattern the
/// suite might grow later: the failure names the string, so it is a finding to look
/// at rather than a trace silently misread.
pub fn pins(s: &str) -> Result<(bool, bool, bool, bool), JsonError> {
    match s {
        "----" => Ok((false, false, false, false)),
        "r-m-" => Ok((true, false, true, false)),
        "-wm-" => Ok((false, true, true, false)),
        "r--i" => Ok((true, false, false, true)),
        "-w-i" => Ok((false, true, false, true)),
        _ => err(format!("unknown pin string {s:?}")),
    }
}

/// A cursor over the JSON text.
struct Sc<'a> {
    s: &'a str,
    at: usize,
}

impl<'a> Sc<'a> {
    fn ws(&mut self) {
        while self.at < self.s.len() && self.s.as_bytes()[self.at].is_ascii_whitespace() {
            self.at += 1;
        }
    }

    fn eat(&mut self, c: u8) -> Result<(), JsonError> {
        self.ws();
        if self.s.as_bytes().get(self.at) == Some(&c) {
            self.at += 1;
            Ok(())
        } else {
            err(format!("expected {:?} at byte {}", c as char, self.at))
        }
    }

    fn peek(&mut self) -> Option<u8> {
        self.ws();
        self.s.as_bytes().get(self.at).copied()
    }

    /// Reads a `"quoted"` string. The suite's strings have no escapes.
    fn string(&mut self) -> Result<&'a str, JsonError> {
        self.eat(b'"')?;
        let start = self.at;
        while self.at < self.s.len() && self.s.as_bytes()[self.at] != b'"' {
            if self.s.as_bytes()[self.at] == b'\\' {
                return err(format!("escape at byte {} is not supported", self.at));
            }
            self.at += 1;
        }
        if self.at >= self.s.len() {
            return err("unterminated string");
        }
        let out = &self.s[start..self.at];
        self.at += 1;
        Ok(out)
    }

    /// Reads a non-negative integer or `null`. `None` is `null`.
    fn num(&mut self) -> Result<Option<u32>, JsonError> {
        self.ws();
        if self.s[self.at..].starts_with("null") {
            self.at += 4;
            return Ok(None);
        }
        let start = self.at;
        while self.at < self.s.len() && self.s.as_bytes()[self.at].is_ascii_digit() {
            self.at += 1;
        }
        if start == self.at {
            return err(format!("expected a number at byte {start}"));
        }
        self.s[start..self.at]
            .parse::<u32>()
            .map(Some)
            .map_err(|e| JsonError(format!("bad number at byte {start}: {e}")))
    }
}

/// Reads one `[a, b, ...]` array of numbers, of a known length.
fn tuple<const N: usize>(sc: &mut Sc) -> Result<[Option<u32>; N], JsonError> {
    sc.eat(b'[')?;
    let mut out = [None; N];
    for (i, slot) in out.iter_mut().enumerate() {
        if i > 0 {
            sc.eat(b',')?;
        }
        *slot = sc.num()?;
    }
    sc.eat(b']')?;
    Ok(out)
}

fn need(v: Option<u32>, what: &str) -> Result<u32, JsonError> {
    v.ok_or_else(|| JsonError(format!("{what} must not be null")))
}

/// The 26 state keys, in the bit order [`state`] marks them in.
const KEYS: [&str; 26] = [
    "ram", "pc", "sp", "ix", "iy", "wz", "af_", "bc_", "de_", "hl_", "a", "b", "c", "d", "e", "f",
    "h", "l", "i", "r", "ei", "im", "p", "q", "iff1", "iff2",
];

/// Reads a state object: all 26 keys, in whatever order they appear.
fn state(sc: &mut Sc) -> Result<State, JsonError> {
    let mut s = State::default();
    let mut seen = 0u32;
    sc.eat(b'{')?;
    loop {
        let key = sc.string()?;
        sc.eat(b':')?;
        if key == "ram" {
            seen |= 1;
            sc.eat(b'[')?;
            while sc.peek() == Some(b'[') {
                let [a, v] = tuple::<2>(sc)?;
                s.ram.push(RamEntry {
                    addr: u16::try_from(need(a, "ram address")?)
                        .map_err(|e| JsonError(format!("ram address: {e}")))?,
                    val: u8::try_from(need(v, "ram value")?)
                        .map_err(|e| JsonError(format!("ram value: {e}")))?,
                });
                if sc.peek() == Some(b',') {
                    sc.eat(b',')?;
                }
            }
            sc.eat(b']')?;
        } else {
            let n = need(sc.num()?, key)?;
            let as16 = |n: u32| -> Result<u16, JsonError> {
                u16::try_from(n).map_err(|_| JsonError(format!("{key} = {n} exceeds u16")))
            };
            let as8 = |n: u32| -> Result<u8, JsonError> {
                u8::try_from(n).map_err(|_| JsonError(format!("{key} = {n} exceeds u8")))
            };
            let bit = match key {
                "pc" => {
                    s.pc = as16(n)?;
                    1
                }
                "sp" => {
                    s.sp = as16(n)?;
                    2
                }
                "ix" => {
                    s.ix = as16(n)?;
                    3
                }
                "iy" => {
                    s.iy = as16(n)?;
                    4
                }
                "wz" => {
                    s.wz = as16(n)?;
                    5
                }
                "af_" => {
                    s.af_ = as16(n)?;
                    6
                }
                "bc_" => {
                    s.bc_ = as16(n)?;
                    7
                }
                "de_" => {
                    s.de_ = as16(n)?;
                    8
                }
                "hl_" => {
                    s.hl_ = as16(n)?;
                    9
                }
                "a" => {
                    s.a = as8(n)?;
                    10
                }
                "b" => {
                    s.b = as8(n)?;
                    11
                }
                "c" => {
                    s.c = as8(n)?;
                    12
                }
                "d" => {
                    s.d = as8(n)?;
                    13
                }
                "e" => {
                    s.e = as8(n)?;
                    14
                }
                "f" => {
                    s.f = as8(n)?;
                    15
                }
                "h" => {
                    s.h = as8(n)?;
                    16
                }
                "l" => {
                    s.l = as8(n)?;
                    17
                }
                "i" => {
                    s.i = as8(n)?;
                    18
                }
                "r" => {
                    s.r = as8(n)?;
                    19
                }
                "ei" => {
                    s.ei = as8(n)?;
                    20
                }
                "im" => {
                    s.im = as8(n)?;
                    21
                }
                "p" => {
                    s.p = as8(n)?;
                    22
                }
                "q" => {
                    s.q = as8(n)?;
                    23
                }
                "iff1" => {
                    s.iff1 = n != 0;
                    24
                }
                "iff2" => {
                    s.iff2 = n != 0;
                    25
                }
                other => return err(format!("unknown state key {other:?}")),
            };
            seen |= 1 << bit;
        }
        if sc.peek() == Some(b',') {
            sc.eat(b',')?;
        } else {
            break;
        }
    }
    sc.eat(b'}')?;
    for (b, name) in KEYS.iter().enumerate() {
        if seen & (1 << b) == 0 {
            return err(format!("state is missing {name:?}"));
        }
    }
    Ok(s)
}

/// Parses a whole vector JSON file into cases.
///
/// # Errors
///
/// [`JsonError`] naming whatever the reader did not recognise: an unknown key, an
/// unknown pin string or port direction, a missing state key, a number wider than
/// the field it lands in, or a syntactic surprise with the byte offset.
pub fn parse(text: &str) -> Result<Vec<Case>, JsonError> {
    let sc = &mut Sc { s: text, at: 0 };
    sc.eat(b'[')?;
    let mut out = Vec::new();
    while sc.peek() == Some(b'{') {
        out.push(case(sc)?);
        if sc.peek() == Some(b',') {
            sc.eat(b',')?;
        }
    }
    sc.eat(b']')?;
    Ok(out)
}

fn case(sc: &mut Sc) -> Result<Case, JsonError> {
    let mut c = Case::default();
    let (mut got_i, mut got_f, mut got_c) = (false, false, false);
    sc.eat(b'{')?;
    loop {
        let key = sc.string()?;
        sc.eat(b':')?;
        match key {
            // Dropped: recoverable from the filename and the case index.
            "name" => {
                sc.string()?;
            }
            "initial" => {
                c.initial = state(sc)?;
                got_i = true;
            }
            "final" => {
                c.final_ = state(sc)?;
                got_f = true;
            }
            "cycles" => {
                sc.eat(b'[')?;
                while sc.peek() == Some(b'[') {
                    sc.eat(b'[')?;
                    let addr = need(sc.num()?, "cycle address")?;
                    sc.eat(b',')?;
                    let data = sc.num()?;
                    sc.eat(b',')?;
                    let p = sc.string()?;
                    sc.eat(b']')?;
                    let (rd, wr, mreq, ioreq) = pins(p)?;
                    c.cycles.push(Cycle {
                        addr: u16::try_from(addr)
                            .map_err(|_| JsonError(format!("cycle address {addr} exceeds u16")))?,
                        data: match data {
                            None => None,
                            Some(d) => Some(
                                u8::try_from(d)
                                    .map_err(|_| JsonError(format!("cycle data {d} exceeds u8")))?,
                            ),
                        },
                        rd,
                        wr,
                        mreq,
                        ioreq,
                    });
                    if sc.peek() == Some(b',') {
                        sc.eat(b',')?;
                    }
                }
                sc.eat(b']')?;
                got_c = true;
            }
            "ports" => {
                sc.eat(b'[')?;
                while sc.peek() == Some(b'[') {
                    sc.eat(b'[')?;
                    let addr = need(sc.num()?, "port address")?;
                    sc.eat(b',')?;
                    let val = need(sc.num()?, "port value")?;
                    sc.eat(b',')?;
                    let dir = sc.string()?;
                    sc.eat(b']')?;
                    c.ports.push(Port {
                        addr: u16::try_from(addr)
                            .map_err(|_| JsonError(format!("port address {addr} exceeds u16")))?,
                        val: u8::try_from(val)
                            .map_err(|_| JsonError(format!("port value {val} exceeds u8")))?,
                        out: match dir {
                            "w" => true,
                            "r" => false,
                            o => return err(format!("unknown port direction {o:?}")),
                        },
                    });
                    if sc.peek() == Some(b',') {
                        sc.eat(b',')?;
                    }
                }
                sc.eat(b']')?;
            }
            other => return err(format!("unknown case key {other:?}")),
        }
        if sc.peek() == Some(b',') {
            sc.eat(b',')?;
        } else {
            break;
        }
    }
    sc.eat(b'}')?;
    for (ok, what) in [(got_i, "initial"), (got_f, "final"), (got_c, "cycles")] {
        if !ok {
            return err(format!("case is missing {what:?}"));
        }
    }
    Ok(c)
}

#[cfg(test)]
mod tests {
    use super::*;

    const ONE: &str = r#"[
      {
        "name": "00 0000",
        "initial": {"pc": 22437, "sp": 4361, "a": 143, "b": 5, "c": 33,
                    "d": 179, "e": 91, "f": 165, "h": 226, "l": 5,
                    "i": 22, "r": 118, "ix": 61425, "iy": 20946, "wz": 5678,
                    "af_": 4386, "bc_": 5678, "de_": 39030, "hl_": 65261,
                    "ei": 0, "im": 0, "p": 0, "q": 0, "iff1": 0, "iff2": 1,
                    "ram": [[22437, 0]]},
        "final": {"pc": 22438, "sp": 4361, "a": 143, "b": 5, "c": 33,
                  "d": 179, "e": 91, "f": 165, "h": 226, "l": 5,
                  "i": 22, "r": 119, "ix": 61425, "iy": 20946, "wz": 5678,
                  "af_": 4386, "bc_": 5678, "de_": 39030, "hl_": 65261,
                  "ei": 0, "im": 0, "p": 0, "q": 0, "iff1": 0, "iff2": 1,
                  "ram": [[22437, 0]]},
        "cycles": [[22437, null, "----"], [22437, null, "r-m-"],
                   [22437, 0, "----"], [22437, null, "----"]]
      }
    ]"#;

    /// Every field of a case survives the conversion.
    ///
    /// Asserted field by field rather than against a `Case` literal, because a
    /// whole-struct comparison built from the same reading of the JSON would agree
    /// with a reader that transposed two keys. `r` is 118 in, 119 out — the M1
    /// refresh increment — and that asymmetry is what proves `initial` and `final`
    /// were not read from the same object.
    #[test]
    fn a_case_converts_field_by_field() {
        let cs = parse(ONE).expect("parses");
        assert_eq!(cs.len(), 1);
        let c = &cs[0];
        assert_eq!(c.initial.pc, 22437);
        assert_eq!(c.final_.pc, 22438, "final, not initial");
        assert_eq!(c.initial.r, 118);
        assert_eq!(c.final_.r, 119, "M1 bumped the refresh counter");
        assert_eq!(c.initial.i, 22);
        assert_eq!(c.initial.ix, 61425);
        assert_eq!(c.initial.iy, 20946);
        assert_eq!(c.initial.wz, 5678);
        assert_eq!(c.initial.af_, 4386);
        assert_eq!(c.initial.hl_, 65261);
        assert_eq!((c.initial.a, c.initial.f), (143, 165));
        assert_eq!((c.initial.b, c.initial.c), (5, 33));
        assert_eq!((c.initial.d, c.initial.e), (179, 91));
        assert_eq!((c.initial.h, c.initial.l), (226, 5));
        assert!(!c.initial.iff1, "0 is false");
        assert!(c.initial.iff2, "1 is true, and they differ here on purpose");
        assert_eq!(
            c.initial.ram,
            vec![RamEntry {
                addr: 22437,
                val: 0
            }]
        );
        assert!(c.ports.is_empty(), "absent ports is empty, not an error");
    }

    /// The pin string becomes four booleans, and `null` data becomes `None`.
    ///
    /// The third sample carries data with **no pins set** — that is the format's
    /// trap, and it is asserted here rather than described.
    ///
    /// The fixture's `r-m-` sample carries `null`, which is what the suite does:
    /// measured across six files, `r-m-` was null in 15,000 of 15,000 samples. An
    /// earlier draft of this fixture put the fetched byte on the read request and
    /// the settled `----` sample both; that is a trace no real file contains, and
    /// writing it here would have taught the reader's tests a shape the reader will
    /// never see.
    #[test]
    fn the_pin_string_becomes_pins_and_null_becomes_none() {
        let cs = parse(ONE).expect("parses");
        let c = &cs[0];
        assert_eq!(c.cycles.len(), 4, "NOP is 4 T-states");
        assert_eq!(c.cycles[0].data, None);
        assert!(!c.cycles[0].rd && !c.cycles[0].mreq, "---- is internal");
        assert!(c.cycles[1].rd && c.cycles[1].mreq, "r-m- is a read request");
        assert_eq!(c.cycles[1].data, None, "and it carries no byte");
        assert_eq!(
            c.cycles[2].data,
            Some(0),
            "the byte lands on a later sample"
        );
        assert!(!c.cycles[2].rd, "with no pins asserted at all");
    }

    /// The five pin patterns the suite uses, each decoded.
    #[test]
    fn every_pin_pattern_the_suite_uses_decodes() {
        for (s, want) in [
            ("----", (false, false, false, false)),
            ("r-m-", (true, false, true, false)),
            ("-wm-", (false, true, true, false)),
            ("r--i", (true, false, false, true)),
            ("-w-i", (false, true, false, true)),
        ] {
            let got = pins(s).unwrap_or_else(|_| panic!("{s} must decode"));
            assert_eq!(got, want, "pins {s:?}");
        }
    }

    /// An unrecognised pin string is an error naming it, never a default.
    ///
    /// The suite could grow a pattern — BUSACK, or a HALT indication — and a reader
    /// that silently decoded the unknown as "no pins" would compare a core against
    /// a trace it had misread, and pass.
    #[test]
    fn an_unknown_pin_string_is_a_loud_error() {
        let e = pins("rwmi").expect_err("must reject");
        assert!(e.to_string().contains("rwmi"), "{e}");
        assert!(pins("--").is_err(), "wrong length is wrong");
        assert!(pins("").is_err());
        // The four combinations a per-character decoder would wave through. Each
        // asserts two pins that are never low together on real silicon: RD with WR,
        // or MREQ with IORQ.
        for s in ["rw--", "--mi", "rwm-", "r-mi"] {
            assert!(pins(s).is_err(), "{s:?} is not a pattern the suite emits");
        }
    }

    /// A port transaction's direction comes from the token, and only two are known.
    #[test]
    fn a_port_direction_is_r_or_w_and_nothing_else() {
        let txt = ONE.replace(
            r#""cycles":"#,
            r#""ports": [[43982, 90, "w"], [4660, 7, "r"]], "cycles":"#,
        );
        let cs = parse(&txt).expect("parses");
        let c = &cs[0];
        assert_eq!(c.ports.len(), 2);
        assert_eq!(
            c.ports[0],
            Port {
                addr: 43982,
                val: 90,
                out: true
            }
        );
        assert_eq!(
            c.ports[1],
            Port {
                addr: 4660,
                val: 7,
                out: false
            }
        );

        let bad = ONE.replace(r#""cycles":"#, r#""ports": [[1, 2, "x"]], "cycles":"#);
        assert!(parse(&bad).is_err(), "an unknown direction is an error");
    }

    /// Removes the first `"key": value` pair from a JSON fixture, brackets and all.
    ///
    /// *Renaming* the key would not test what the caller claims: the reader would
    /// reject it as an **unknown** key, naming the new name, so an assertion that
    /// the message names the original key would fail. Deleting the pair outright is
    /// what makes the reader reach its missing-key check.
    fn without(text: &str, key: &str) -> String {
        let pat = format!("\"{key}\":");
        let start = text
            .find(&pat)
            .unwrap_or_else(|| panic!("fixture has no {key:?}"));
        let b = text.as_bytes();
        let mut i = start + pat.len();
        let mut depth = 0i32;
        // Scan to whichever comes first: the comma ending this pair, or the `}`
        // closing the enclosing object — which means this pair was the last one and
        // the comma to remove is the one *before* it.
        let (end, was_last) = loop {
            assert!(i < b.len(), "fixture ended mid-value after {key:?}");
            match b[i] {
                b'[' | b'{' => depth += 1,
                b']' | b'}' if depth == 0 => break (i, true),
                b']' | b'}' => depth -= 1,
                b',' if depth == 0 => break (i + 1, false),
                _ => {}
            }
            i += 1;
        };
        let mut left = text[..start].trim_end().to_string();
        if was_last {
            assert!(left.ends_with(','), "a last pair must follow a comma");
            left.pop();
        }
        left + &text[end..]
    }

    /// A missing key is an error naming the key.
    ///
    /// One test per key would be 26 near-identical tests; this removes each in turn
    /// from the same fixture, which also means a key added later is covered without
    /// editing the test.
    ///
    /// The expected message is matched in its **quoted** form. Twelve of the keys are
    /// one character — `a`, `b`, `r`, `i` — and a bare `contains("a")` would be
    /// satisfied by "expected ',' at byte 12". That is an assertion that cannot
    /// fail: it would hold for a reader that reported a syntax error at the wrong
    /// place instead of the missing key.
    #[test]
    fn every_missing_state_key_is_an_error_naming_it() {
        for key in KEYS {
            let broken = without(ONE, key);
            assert_ne!(broken, ONE, "{key:?} must actually have been removed");
            let e = match parse(&broken) {
                Err(e) => e,
                Ok(_) => panic!("a case missing {key:?} must not parse"),
            };
            let want = format!("state is missing {key:?}");
            assert_eq!(e.to_string(), want, "for a missing {key:?}");
        }
    }

    /// A case missing a whole section is an error naming the section.
    #[test]
    fn every_missing_case_key_is_an_error_naming_it() {
        for key in ["initial", "final", "cycles"] {
            let broken = without(ONE, key);
            let e = match parse(&broken) {
                Err(e) => e,
                Ok(_) => panic!("a case missing {key:?} must not parse"),
            };
            let want = format!("case is missing {key:?}");
            assert_eq!(e.to_string(), want, "for a missing {key:?}");
        }
    }
}
